/* The following code was generated by JFlex 1.4.1 on 01.06.08 01:46 */

package org.lqc.jxc;

import java_cup.runtime.*;
import org.lqc.jxc.tokens.*;
import org.lqc.jxc.types.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 01.06.08 01:46 from the specification file
 * <tt>E:/workspaces/mimuw/jxc/jflex/Scanner.jflex</tt>
 */
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 1;
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\7\1\3\1\2\1\0\1\3\1\1\16\7\4\0\1\3\1\22"+
    "\1\56\1\20\1\6\1\30\1\32\1\0\1\13\1\14\1\27\1\25"+
    "\1\17\1\26\1\11\1\4\1\5\11\10\1\0\1\12\1\23\1\21"+
    "\1\24\2\0\32\6\1\0\1\57\2\0\1\6\1\0\1\44\1\41"+
    "\1\6\1\36\1\43\1\51\1\47\1\53\1\33\2\6\1\42\1\54"+
    "\1\34\1\37\1\55\1\6\1\46\1\45\1\35\1\40\1\50\1\52"+
    "\3\6\1\15\1\31\1\16\1\0\41\7\2\0\4\6\4\0\1\6"+
    "\2\0\1\7\7\0\1\6\4\0\1\6\5\0\27\6\1\0\37\6"+
    "\1\0\u013f\6\31\0\162\6\4\0\14\6\16\0\5\6\11\0\1\6"+
    "\21\0\130\7\5\0\23\7\12\0\1\6\13\0\1\6\1\0\3\6"+
    "\1\0\1\6\1\0\24\6\1\0\54\6\1\0\46\6\1\0\5\6"+
    "\4\0\202\6\1\0\4\7\3\0\105\6\1\0\46\6\2\0\2\6"+
    "\6\0\20\6\41\0\46\6\2\0\1\6\7\0\47\6\11\0\21\7"+
    "\1\0\27\7\1\0\3\7\1\0\1\7\1\0\2\7\1\0\1\7"+
    "\13\0\33\6\5\0\3\6\15\0\4\7\14\0\6\7\13\0\32\6"+
    "\5\0\13\6\16\7\7\0\12\7\4\0\2\6\1\7\143\6\1\0"+
    "\1\6\10\7\1\0\6\7\2\6\2\7\1\0\4\7\2\6\12\7"+
    "\3\6\2\0\1\6\17\0\1\7\1\6\1\7\36\6\33\7\2\0"+
    "\3\6\60\0\46\6\13\7\1\6\u014f\0\3\7\66\6\2\0\1\7"+
    "\1\6\20\7\2\0\1\6\4\7\3\0\12\6\2\7\2\0\12\7"+
    "\21\0\3\7\1\0\10\6\2\0\2\6\2\0\26\6\1\0\7\6"+
    "\1\0\1\6\3\0\4\6\2\0\1\7\1\6\7\7\2\0\2\7"+
    "\2\0\3\7\11\0\1\7\4\0\2\6\1\0\3\6\2\7\2\0"+
    "\12\7\4\6\15\0\3\7\1\0\6\6\4\0\2\6\2\0\26\6"+
    "\1\0\7\6\1\0\2\6\1\0\2\6\1\0\2\6\2\0\1\7"+
    "\1\0\5\7\4\0\2\7\2\0\3\7\13\0\4\6\1\0\1\6"+
    "\7\0\14\7\3\6\14\0\3\7\1\0\11\6\1\0\3\6\1\0"+
    "\26\6\1\0\7\6\1\0\2\6\1\0\5\6\2\0\1\7\1\6"+
    "\10\7\1\0\3\7\1\0\3\7\2\0\1\6\17\0\2\6\2\7"+
    "\2\0\12\7\1\0\1\6\17\0\3\7\1\0\10\6\2\0\2\6"+
    "\2\0\26\6\1\0\7\6\1\0\2\6\1\0\5\6\2\0\1\7"+
    "\1\6\6\7\3\0\2\7\2\0\3\7\10\0\2\7\4\0\2\6"+
    "\1\0\3\6\4\0\12\7\1\0\1\6\20\0\1\7\1\6\1\0"+
    "\6\6\3\0\3\6\1\0\4\6\3\0\2\6\1\0\1\6\1\0"+
    "\2\6\3\0\2\6\3\0\3\6\3\0\10\6\1\0\3\6\4\0"+
    "\5\7\3\0\3\7\1\0\4\7\11\0\1\7\17\0\11\7\11\0"+
    "\1\6\7\0\3\7\1\0\10\6\1\0\3\6\1\0\27\6\1\0"+
    "\12\6\1\0\5\6\4\0\7\7\1\0\3\7\1\0\4\7\7\0"+
    "\2\7\11\0\2\6\4\0\12\7\22\0\2\7\1\0\10\6\1\0"+
    "\3\6\1\0\27\6\1\0\12\6\1\0\5\6\2\0\1\7\1\6"+
    "\7\7\1\0\3\7\1\0\4\7\7\0\2\7\7\0\1\6\1\0"+
    "\2\6\4\0\12\7\22\0\2\7\1\0\10\6\1\0\3\6\1\0"+
    "\27\6\1\0\20\6\4\0\6\7\2\0\3\7\1\0\4\7\11\0"+
    "\1\7\10\0\2\6\4\0\12\7\22\0\2\7\1\0\22\6\3\0"+
    "\30\6\1\0\11\6\1\0\1\6\2\0\7\6\3\0\1\7\4\0"+
    "\6\7\1\0\1\7\1\0\10\7\22\0\2\7\15\0\60\6\1\7"+
    "\2\6\7\7\4\0\10\6\10\7\1\0\12\7\47\0\2\6\1\0"+
    "\1\6\2\0\2\6\1\0\1\6\2\0\1\6\6\0\4\6\1\0"+
    "\7\6\1\0\3\6\1\0\1\6\1\0\1\6\2\0\2\6\1\0"+
    "\4\6\1\7\2\6\6\7\1\0\2\7\1\6\2\0\5\6\1\0"+
    "\1\6\1\0\6\7\2\0\12\7\2\0\2\6\42\0\1\6\27\0"+
    "\2\7\6\0\12\7\13\0\1\7\1\0\1\7\1\0\1\7\4\0"+
    "\2\7\10\6\1\0\42\6\6\0\24\7\1\0\2\7\4\6\4\0"+
    "\10\7\1\0\44\7\11\0\1\7\71\0\42\6\1\0\5\6\1\0"+
    "\2\6\1\0\7\7\3\0\4\7\6\0\12\7\6\0\6\6\4\7"+
    "\106\0\46\6\12\0\51\6\7\0\132\6\5\0\104\6\5\0\122\6"+
    "\6\0\7\6\1\0\77\6\1\0\1\6\1\0\4\6\2\0\7\6"+
    "\1\0\1\6\1\0\4\6\2\0\47\6\1\0\1\6\1\0\4\6"+
    "\2\0\37\6\1\0\1\6\1\0\4\6\2\0\7\6\1\0\1\6"+
    "\1\0\4\6\2\0\7\6\1\0\7\6\1\0\27\6\1\0\37\6"+
    "\1\0\1\6\1\0\4\6\2\0\7\6\1\0\47\6\1\0\23\6"+
    "\16\0\11\7\56\0\125\6\14\0\u026c\6\2\0\10\6\12\0\32\6"+
    "\5\0\113\6\3\0\3\6\17\0\15\6\1\0\4\6\3\7\13\0"+
    "\22\6\3\7\13\0\22\6\2\7\14\0\15\6\1\0\3\6\1\0"+
    "\2\7\14\0\64\6\40\7\3\0\1\6\3\0\2\6\1\7\2\0"+
    "\12\7\41\0\3\7\2\0\12\7\6\0\130\6\10\0\51\6\1\7"+
    "\126\0\35\6\3\0\14\7\4\0\14\7\12\0\12\7\36\6\2\0"+
    "\5\6\u038b\0\154\6\224\0\234\6\4\0\132\6\6\0\26\6\2\0"+
    "\6\6\2\0\46\6\2\0\6\6\2\0\10\6\1\0\1\6\1\0"+
    "\1\6\1\0\1\6\1\0\37\6\2\0\65\6\1\0\7\6\1\0"+
    "\1\6\3\0\3\6\1\0\7\6\3\0\4\6\2\0\6\6\4\0"+
    "\15\6\5\0\3\6\1\0\7\6\17\0\4\7\32\0\5\7\20\0"+
    "\2\6\23\0\1\6\13\0\4\7\6\0\6\7\1\0\1\6\15\0"+
    "\1\6\40\0\22\6\36\0\15\7\4\0\1\7\3\0\6\7\27\0"+
    "\1\6\4\0\1\6\2\0\12\6\1\0\1\6\3\0\5\6\6\0"+
    "\1\6\1\0\1\6\1\0\1\6\1\0\4\6\1\0\3\6\1\0"+
    "\7\6\3\0\3\6\5\0\5\6\26\0\44\6\u0e81\0\3\6\31\0"+
    "\11\6\6\7\1\0\5\6\2\0\5\6\4\0\126\6\2\0\2\7"+
    "\2\0\3\6\1\0\137\6\5\0\50\6\4\0\136\6\21\0\30\6"+
    "\70\0\20\6\u0200\0\u19b6\6\112\0\u51a6\6\132\0\u048d\6\u0773\0\u2ba4\6"+
    "\u215c\0\u012e\6\2\0\73\6\225\0\7\6\14\0\5\6\5\0\1\6"+
    "\1\7\12\6\1\0\15\6\1\0\5\6\1\0\1\6\1\0\2\6"+
    "\1\0\2\6\1\0\154\6\41\0\u016b\6\22\0\100\6\2\0\66\6"+
    "\50\0\15\6\3\0\20\7\20\0\4\7\17\0\2\6\30\0\3\6"+
    "\31\0\1\6\6\0\5\6\1\0\207\6\2\0\1\7\4\0\1\6"+
    "\13\0\12\7\7\0\32\6\4\0\1\6\1\0\32\6\12\0\132\6"+
    "\3\0\6\6\2\0\6\6\2\0\6\6\2\0\3\6\3\0\2\6"+
    "\3\0\2\6\22\0\3\7\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\2\2\1\3\1\4\1\5\1\4\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\2\1"+
    "\12\5\1\26\1\27\1\30\1\31\2\32\2\0\1\33"+
    "\1\0\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\5\1\45\14\5\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\2\54\1\55\1\56\10\5\1\57"+
    "\1\60\3\5\1\61\2\5\1\62\2\5\1\63\7\5"+
    "\1\64\1\65\1\66\1\67\1\5\1\70\1\71\1\72";

  private static int [] zzUnpackAction() {
    int [] result = new int[116];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\140\0\220\0\300\0\220\0\360\0\u0120"+
    "\0\u0150\0\u0180\0\220\0\220\0\220\0\220\0\220\0\220"+
    "\0\220\0\220\0\u01b0\0\u01e0\0\u0210\0\u0240\0\u0270\0\u02a0"+
    "\0\220\0\220\0\u02d0\0\u0300\0\u0330\0\u0360\0\u0390\0\u03c0"+
    "\0\u03f0\0\u0420\0\u0450\0\u0480\0\u04b0\0\u04e0\0\220\0\u0510"+
    "\0\220\0\u0540\0\220\0\u0570\0\u05a0\0\u05d0\0\220\0\u0600"+
    "\0\220\0\220\0\220\0\220\0\220\0\220\0\220\0\220"+
    "\0\220\0\u0630\0\u0150\0\u0660\0\u0690\0\u06c0\0\u06f0\0\u0720"+
    "\0\u0750\0\u0780\0\u07b0\0\u07e0\0\u0810\0\u0840\0\u0870\0\220"+
    "\0\220\0\220\0\220\0\220\0\220\0\u08a0\0\220\0\u0600"+
    "\0\u0150\0\u08d0\0\u0900\0\u0930\0\u0960\0\u0990\0\u09c0\0\u09f0"+
    "\0\u0a20\0\u0150\0\u0150\0\u0a50\0\u0a80\0\u0ab0\0\u0150\0\u0ae0"+
    "\0\u0b10\0\u0150\0\u0b40\0\u0b70\0\u0150\0\u0ba0\0\u0bd0\0\u0c00"+
    "\0\u0c30\0\u0c60\0\u0c90\0\u0cc0\0\u0150\0\u0150\0\u0150\0\u0150"+
    "\0\u0cf0\0\u0150\0\u0150\0\u0150";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[116];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\2\6\1\7\1\10\1\11\1\4\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\11\1\36\1\37\2\11\1\40"+
    "\1\11\1\41\1\11\1\42\1\43\1\11\1\44\1\45"+
    "\1\46\3\11\1\47\1\4\1\50\2\0\53\50\1\51"+
    "\1\52\4\53\1\54\22\53\1\55\30\53\62\0\1\6"+
    "\61\0\1\56\22\0\1\57\41\0\1\60\53\0\4\11"+
    "\22\0\23\11\7\0\1\12\2\0\1\12\1\60\67\0"+
    "\1\61\57\0\1\62\57\0\1\63\57\0\1\64\63\0"+
    "\1\65\56\0\1\66\1\0\1\67\62\0\1\70\60\0"+
    "\1\71\32\0\4\11\22\0\1\11\1\72\14\11\1\73"+
    "\2\11\1\74\1\11\7\0\4\11\22\0\13\11\1\75"+
    "\7\11\7\0\4\11\22\0\4\11\1\76\16\11\7\0"+
    "\4\11\22\0\4\11\1\77\16\11\7\0\4\11\22\0"+
    "\7\11\1\100\13\11\7\0\4\11\22\0\2\11\1\101"+
    "\20\11\7\0\4\11\22\0\10\11\1\102\12\11\7\0"+
    "\4\11\22\0\4\11\1\103\16\11\7\0\4\11\22\0"+
    "\4\11\1\104\1\105\3\11\1\106\11\11\7\0\4\11"+
    "\22\0\20\11\1\107\2\11\2\0\1\50\2\0\53\50"+
    "\36\0\1\110\1\111\10\0\1\112\7\0\1\113\30\0"+
    "\1\114\30\0\4\53\1\115\53\53\1\56\1\116\1\117"+
    "\55\56\5\0\1\120\2\0\1\120\54\0\4\11\22\0"+
    "\2\11\1\121\20\11\7\0\4\11\22\0\22\11\1\122"+
    "\7\0\4\11\22\0\5\11\1\123\15\11\7\0\4\11"+
    "\22\0\5\11\1\124\15\11\7\0\4\11\22\0\4\11"+
    "\1\125\16\11\7\0\4\11\22\0\12\11\1\126\10\11"+
    "\7\0\4\11\22\0\13\11\1\127\7\11\7\0\4\11"+
    "\22\0\2\11\1\130\20\11\7\0\4\11\22\0\1\131"+
    "\22\11\7\0\4\11\22\0\13\11\1\132\7\11\7\0"+
    "\4\11\22\0\1\11\1\133\21\11\7\0\4\11\22\0"+
    "\7\11\1\134\13\11\7\0\4\11\22\0\1\135\22\11"+
    "\4\0\1\117\62\0\4\11\22\0\4\11\1\136\16\11"+
    "\7\0\4\11\22\0\10\11\1\137\12\11\7\0\4\11"+
    "\22\0\6\11\1\140\14\11\7\0\4\11\22\0\7\11"+
    "\1\141\13\11\7\0\4\11\22\0\10\11\1\142\12\11"+
    "\7\0\4\11\22\0\1\143\22\11\7\0\4\11\22\0"+
    "\5\11\1\144\15\11\7\0\4\11\22\0\3\11\1\145"+
    "\17\11\7\0\4\11\22\0\12\11\1\146\10\11\7\0"+
    "\4\11\22\0\7\11\1\147\13\11\7\0\4\11\22\0"+
    "\13\11\1\150\7\11\7\0\4\11\22\0\7\11\1\151"+
    "\13\11\7\0\4\11\22\0\10\11\1\152\12\11\7\0"+
    "\4\11\22\0\1\11\1\153\21\11\7\0\4\11\22\0"+
    "\13\11\1\154\7\11\7\0\4\11\22\0\10\11\1\155"+
    "\12\11\7\0\4\11\22\0\10\11\1\156\12\11\7\0"+
    "\4\11\22\0\2\11\1\157\20\11\7\0\4\11\22\0"+
    "\10\11\1\160\12\11\7\0\4\11\22\0\11\11\1\161"+
    "\11\11\7\0\4\11\22\0\14\11\1\162\6\11\7\0"+
    "\4\11\22\0\1\11\1\163\21\11\7\0\4\11\22\0"+
    "\1\11\1\164\21\11\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3360];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\1\1\1\11\4\1\10\11\6\1\2\11"+
    "\14\1\1\11\1\1\1\11\1\1\1\11\1\1\2\0"+
    "\1\11\1\0\11\11\16\1\6\11\1\1\1\11\45\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[116];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
	public Lexem newSymbol(String name, int id) {
		return new Lexem(name, id, yyline, yycolumn);
	}	
	
	public Lexem newSymbol(String name, int id, Object v) {
		return new Lexem(name, id, yyline, yycolumn, v);
	}			
	
	private StringBuffer string = new StringBuffer();
	private int comment_level = 0;
	public String srcFilename;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
  	yybegin(YYINITIAL);
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1750) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public org.lqc.jxc.Lexem next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 20: 
          { return newSymbol(yytext(), sym.TIMES);
          }
        case 59: break;
        case 56: 
          { return newSymbol(yytext(), sym.PTYPE, PrimitiveType.STRING);
          }
        case 60: break;
        case 55: 
          { return newSymbol(yytext(), sym.PTYPE, PrimitiveType.REAL);
          }
        case 61: break;
        case 22: 
          { yybegin(STRING); string = new StringBuffer();
          }
        case 62: break;
        case 29: 
          { return newSymbol(yytext(), sym.NEQEQ);
          }
        case 63: break;
        case 43: 
          { comment_level--;					    
					  if(comment_level == 0) yybegin(YYINITIAL);
          }
        case 64: break;
        case 27: 
          { yybegin(COMMENT); comment_level = 1;
          }
        case 65: break;
        case 14: 
          { return newSymbol(yytext(), sym.EQUAL);
          }
        case 66: break;
        case 58: 
          { return newSymbol(yytext(), sym.PTYPE, PrimitiveType.BOOLEAN);
          }
        case 67: break;
        case 53: 
          { return newSymbol("Keyword", sym.WHILE);
          }
        case 68: break;
        case 39: 
          { string.append('\t');
          }
        case 69: break;
        case 15: 
          { return newSymbol(yytext(), sym.NEG);
          }
        case 70: break;
        case 10: 
          { return newSymbol(yytext(), sym.LCURLY);
          }
        case 71: break;
        case 52: 
          { return newSymbol("Boolean", sym.BOOLEAN, new Boolean(false));
          }
        case 72: break;
        case 5: 
          { return newSymbol("Identifier", sym.ID, new String(yytext()) );
          }
        case 73: break;
        case 2: 
          { /* ignore white space. */
          }
        case 74: break;
        case 34: 
          { return newSymbol(yytext(), sym.MINUSMINUS);
          }
        case 75: break;
        case 19: 
          { return newSymbol(yytext(), sym.MINUS);
          }
        case 76: break;
        case 13: 
          { return newSymbol(yytext(), sym.HASH);
          }
        case 77: break;
        case 25: 
          { string.append('\\');
          }
        case 78: break;
        case 57: 
          { return newSymbol("Keyword", sym.RETURN);
          }
        case 79: break;
        case 7: 
          { return newSymbol(yytext(), sym.SEMI);
          }
        case 80: break;
        case 4: 
          { return newSymbol("Integer", sym.INT, new Integer(yytext()) );
          }
        case 81: break;
        case 40: 
          { string.append('\r');
          }
        case 82: break;
        case 30: 
          { return newSymbol(yytext(), sym.LTEQ);
          }
        case 83: break;
        case 12: 
          { return newSymbol(yytext(), sym.COMMA);
          }
        case 84: break;
        case 48: 
          { return newSymbol("Keyword", sym.FUN);
          }
        case 85: break;
        case 32: 
          { return newSymbol(yytext(), sym.PLUSPLUS);
          }
        case 86: break;
        case 41: 
          { string.append('\"');
          }
        case 87: break;
        case 24: 
          { yybegin(YYINITIAL); 
					 return newSymbol("String", sym.STRING, string.toString());
          }
        case 88: break;
        case 50: 
          { return newSymbol("Keyword", sym.ELSE);
          }
        case 89: break;
        case 54: 
          { return newSymbol("Keyword", sym.IMPORT);
          }
        case 90: break;
        case 47: 
          { return newSymbol("Keyword", sym.FOR);
          }
        case 91: break;
        case 6: 
          { return newSymbol(yytext(), sym.DOT);
          }
        case 92: break;
        case 33: 
          { return newSymbol(yytext(), sym.RARROW);
          }
        case 93: break;
        case 28: 
          { return newSymbol(yytext(), sym.EQEQ);
          }
        case 94: break;
        case 3: 
          { return newSymbol(yytext(), sym.DIVIDE);
          }
        case 95: break;
        case 42: 
          { comment_level++;
          }
        case 96: break;
        case 45: 
          { return newSymbol("Real", sym.REAL, new Double(yytext()) );
          }
        case 97: break;
        case 11: 
          { return newSymbol(yytext(), sym.RCURLY);
          }
        case 98: break;
        case 38: 
          { string.append('\n');
          }
        case 99: break;
        case 51: 
          { return newSymbol(yytext(), sym.PTYPE, Type.VOID);
          }
        case 100: break;
        case 49: 
          { return newSymbol("Boolean", sym.BOOLEAN, new Boolean(true));
          }
        case 101: break;
        case 8: 
          { return newSymbol(yytext(), sym.LPAR);
          }
        case 102: break;
        case 31: 
          { return newSymbol(yytext(), sym.GTEQ);
          }
        case 103: break;
        case 1: 
          { System.err.println("Illegal character: "+yytext());
          }
        case 104: break;
        case 9: 
          { return newSymbol(yytext(), sym.RPAR);
          }
        case 105: break;
        case 21: 
          { return newSymbol(yytext(), sym.MODULO);
          }
        case 106: break;
        case 46: 
          { return newSymbol(yytext(), sym.PTYPE, PrimitiveType.INT);
          }
        case 107: break;
        case 36: 
          { return newSymbol(yytext(), sym.LOGAND);
          }
        case 108: break;
        case 44: 
          { /* comment */
          }
        case 109: break;
        case 35: 
          { return newSymbol(yytext(), sym.LOGOR);
          }
        case 110: break;
        case 17: 
          { return newSymbol(yytext(), sym.GT);
          }
        case 111: break;
        case 23: 
          { string.append( yytext() );
          }
        case 112: break;
        case 37: 
          { return newSymbol("Keyword", sym.IF);
          }
        case 113: break;
        case 16: 
          { return newSymbol(yytext(), sym.LT);
          }
        case 114: break;
        case 18: 
          { return newSymbol(yytext(), sym.PLUS);
          }
        case 115: break;
        case 26: 
          { 
          }
        case 116: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              {     return newSymbol("EndOfFile", sym.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
