
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 25 21:57:36 CEST 2008
//----------------------------------------------------

package org.lqc.jxc;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int PLUSPLUS = 24;
  public static final int DIVIDE = 19;
  public static final int GTEQ = 15;
  public static final int LOGAND = 27;
  public static final int LTEQ = 13;
  public static final int UMINUS = 23;
  public static final int UPLUS = 22;
  public static final int DEFINES = 38;
  public static final int SEMI = 2;
  public static final int INT = 28;
  public static final int NEQEQ = 11;
  public static final int FOR = 35;
  public static final int MINUS = 17;
  public static final int LT = 12;
  public static final int RPAR = 6;
  public static final int TYPE = 41;
  public static final int PLUS = 16;
  public static final int IF = 33;
  public static final int DOT = 4;
  public static final int ID = 32;
  public static final int EOF = 0;
  public static final int BOOLEAN = 30;
  public static final int RETURN = 37;
  public static final int MINUSMINUS = 25;
  public static final int EQUAL = 9;
  public static final int error = 1;
  public static final int LCURLY = 7;
  public static final int MODULO = 20;
  public static final int EQEQ = 10;
  public static final int RCURLY = 8;
  public static final int IMPORT = 40;
  public static final int REAL = 29;
  public static final int TIMES = 18;
  public static final int COLON = 3;
  public static final int NEG = 21;
  public static final int ELSE = 34;
  public static final int WHILE = 36;
  public static final int LOGOR = 26;
  public static final int LPAR = 5;
  public static final int STRING = 31;
  public static final int IMPLEMENTS = 39;
  public static final int GT = 14;
}

