
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 27 22:22:05 CEST 2008
//----------------------------------------------------

package org.lqc.jxc;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int PLUSPLUS = 23;
  public static final int DIVIDE = 18;
  public static final int GTEQ = 14;
  public static final int LOGAND = 26;
  public static final int LTEQ = 12;
  public static final int UMINUS = 22;
  public static final int UPLUS = 21;
  public static final int SEMI = 2;
  public static final int INT = 27;
  public static final int NEQEQ = 10;
  public static final int FOR = 34;
  public static final int MINUS = 16;
  public static final int LT = 11;
  public static final int RPAR = 5;
  public static final int TYPE = 37;
  public static final int PLUS = 15;
  public static final int IF = 32;
  public static final int ID = 31;
  public static final int EOF = 0;
  public static final int BOOLEAN = 29;
  public static final int RETURN = 36;
  public static final int MINUSMINUS = 24;
  public static final int EQUAL = 8;
  public static final int error = 1;
  public static final int LCURLY = 6;
  public static final int MODULO = 19;
  public static final int EQEQ = 9;
  public static final int RCURLY = 7;
  public static final int REAL = 28;
  public static final int TIMES = 17;
  public static final int COLON = 3;
  public static final int NEG = 20;
  public static final int ELSE = 33;
  public static final int WHILE = 35;
  public static final int LOGOR = 25;
  public static final int LPAR = 4;
  public static final int STRING = 30;
  public static final int GT = 13;
}

